version: '3.8'

services:

  discovery:
    image: discovery:latest
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5


  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    environment:
      EUREKA_SERVER: http://discovery:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

