version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - network.host=0.0.0.0
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network

  user-service:
    image: user-service:latest
    container_name: user-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  book-service:
    image: book-service:latest
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  order-service:
    image: order-service:latest
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  search-service:
    image: search-service:latest
    container_name: search-service
    ports:
      - "8085:8085"
    depends_on:
      - elasticsearch
      - kafka
    networks:
      - app-network

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  discovery:
    image: discovery:latest
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
